// Auto-generated by split-search-index.js
(function () {
  var supported = new Set(["en","es","de","fr","pt","ja","ko","zh"]);
  var versionMap = {"continuous-delivery":["next"],"security":["5.5"],"os-manager":["1.9"],"cluster-api":["v0.26"],"suse-virtual-clusters":["1.1.0"],"admission-controller":["1.35"],"suse-observability":["latest"],"storage":["1.11"],"virtualization":["v1.7"],"rancher-srfa":["latest"],"rancher-manager":["v2.14"],"rancher-ai":["latest"],"rancher-developer-access":["latest"],"rke2":["latest"],"k3s":["latest"]};
  var scriptUrl = (document.currentScript && document.currentScript.src) || '/search-index.js';
  var scriptPathname = new URL(scriptUrl, window.location.href).pathname;
  var pathname = window.location.pathname || '';
  var basePath = scriptPathname.replace(/\/search-index\.js$/, '');
  var relativePathname = pathname.indexOf(basePath + '/') === 0
    ? pathname.slice(basePath.length)
    : pathname;
  var match = relativePathname.match(/^\/([^/]+)\/([^/]+)\/([^/]+)\//);
  var component = match && match[1];
  var version = match && match[2];
  var lang = (match && match[3]) || 'en';

  if (!component || !version) return;
  if (!supported.has(lang)) lang = 'en';

  function inject(componentName, versionName, langCode, usedFallbackVersion) {
    var encodedComponent = encodeURIComponent(componentName);
    var encodedVersion = encodeURIComponent(versionName);
    var url = new URL('lang-indexes/' + encodedComponent + '/' + encodedVersion + '/search-index-' + langCode + '.js', scriptUrl).toString();
    var s = document.createElement('script');
    s.async = true;
    s.src = url;
    s.onerror = function () {
      if (!usedFallbackVersion) {
        var versions = versionMap[componentName] || [];
        for (var i = 0; i < versions.length; i++) {
          if (versions[i] !== versionName) {
            inject(componentName, versions[i], langCode, true);
            return;
          }
        }
      }
      if (langCode !== 'en') inject(componentName, versionName, 'en', usedFallbackVersion);
    };
    document.head.appendChild(s);
  }

  inject(component, version, lang, false);
})();
